// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package guidefs

import "fyne.io/fyne/v2"

var resourceFolderPlaySvg = &fyne.StaticResource{
	StaticName: "folder-play.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\">\n    <path d=\"M22 8V13.81C21.39 13.46 20.72 13.22 20 13.09V8H4V18H13.09C13.04 18.33 13 18.66 13 19C13 19.34 13.04 19.67 13.09 20H4C2.9 20 2 19.11 2 18V6C2 4.89 2.89 4 4 4H10L12 6H20C21.1 6 22 6.89 22 8M17 22L22 19L17 16V22Z\" />\n</svg>"),
}
var resourceFormataligncenterSvg = &fyne.StaticResource{
	StaticName: "format_align_center.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg\n   height=\"24\"\n   viewBox=\"0 0 960 960\"\n   width=\"24\"\n   fill=\"#e8eaed\"\n   xmlns=\"http://www.w3.org/2000/svg\">\n  <path\n     d=\"m 120,840 v -80 h 720 v 80 z M 280,680 v -80 h 400 v 80 z M 120,520 v -80 h 720 v 80 z M 280,360 v -80 h 400 v 80 z M 120,200 v -80 h 720 v 80 z\"\n     id=\"path2\" />\n</svg>\n"),
}
var resourceFormatalignleftSvg = &fyne.StaticResource{
	StaticName: "format_align_left.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg\n   height=\"24\"\n   viewBox=\"0 0 960 960\"\n   width=\"24\"\n   fill=\"#e8eaed\"\n   xmlns=\"http://www.w3.org/2000/svg\">\n  <path\n     d=\"m 120,840 v -80 h 720 v 80 z m 0,-160 v -80 h 480 v 80 z m 0,-160 v -80 h 720 v 80 z m 0,-160 v -80 h 480 v 80 z m 0,-160 v -80 h 720 v 80 z\"\n     id=\"path133\" />\n</svg>\n"),
}
var resourceFormatalignrightSvg = &fyne.StaticResource{
	StaticName: "format_align_right.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg\n   height=\"24\"\n   viewBox=\"0 0 960 960\"\n   width=\"24\"\n   fill=\"#e8eaed\"\n   xmlns=\"http://www.w3.org/2000/svg\">\n  <path\n     d=\"m 120,200 v -80 h 720 v 80 z m 240,160 v -80 h 480 v 80 z M 120,520 v -80 h 720 v 80 z m 240,160 v -80 h 480 v 80 z M 120,840 v -80 h 720 v 80 z\"\n     id=\"path258\" />\n</svg>\n"),
}
